name: Prime Go Module Cache

on:
  workflow_call:
jobs:
  prime_mods:
    name: "Prime Go Modules"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2      
      - uses: magnetikonline/action-golang-cache@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Downloading Go Modules
        run: |
          go mod download
          go mod tidy
