name: tests
on: [push]
env:
  GOBIN: /opt/bin
  GO_VERSION: 1.17.7
jobs:
  preflight:
    uses: ./.github/workflows/prime-mods.yaml
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: magnetikonline/action-golang-cache@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run Vet
        run: |
          go vet ./...
      - name: Run Tests
        run: |
          go test -race -v ./...
